amazon:
  service: S3
  access_key_id: Rails.application.credentials.s3_access_key_id
  secret_access_key: Rails.application.credentials.s3_secret_access_key
  region: Rails.application.credentials.s3_region
  bucket: Rails.application.credentials[Rails.env.to_sym][:s3_bucket]